name: jilr_mobile_sender
description: Mobile client for JILR Email Sender backend
publish_to: 'none'
version: 0.1.2+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: 0.20.2
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.5
  path: ^1.9.1
  app_links: ^6.4.0
  firebase_core: any
  firebase_auth: any
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: assets/icon/app_icon.png
  adaptive_icon_background: "#D9ECF4"
  adaptive_icon_foreground: assets/icon/app_icon.png
  adaptive_icon_foreground_inset: 16

flutter:
  uses-material-design: true
